[tool.isort]
profile = "black"
multi_line_output = 3
order_by_type = false

[tool.mypy]
files = "."
# exclude = "build/.*"
exclude = "tests/.*"

show_error_codes = true

# 'strict = true' is equivalent to the following:
check_untyped_defs = true
# disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
# disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

# The following need to have changes made to be able to enable them:
# disallow_any_generics = true
# disallow_untyped_calls = true
# no_implicit_optional = true
no_implicit_reexport = true
# strict_equality = true
# warn_return_any = true
